config/routes.rb
Rails.application.routes.draw do

  resources :articles
  resources :pinboards
  root 'pinboards#index'

end

app/models/article.rb
class Article < ActiveRecord::Base
  belongs_to :pinboard
end

app/models/pinboard.rb
class Pinboard < ActiveRecord::Base
  has_many :articles
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/article_controller.rb
class ArticleController < ApplicationController
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]

  # GET /articles
  # GET /articles.json
  def index
    @articles = Article.all
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = Article.new(article_params)

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: 'Article was successfully created.' }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1
  # PATCH/PUT /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url, notice: 'Article was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def article_params
      params.require(:article).permit(:title, :content, :pinboard_id)
    end
end

app/controllers/pinboards_controller.rb
class PinboardsController < ApplicationController
  before_action :set_pinboard, only: [:show, :edit, :update, :destroy]

  # GET /pinboards
  # GET /pinboards.json
  def index
    @pinboards = Pinboard.all
  end

  # GET /pinboards/1
  # GET /pinboards/1.json
  def show
  end

  # GET /pinboards/new
  def new
    @pinboard = Pinboard.new
  end

  # GET /pinboards/1/edit
  def edit
  end

  # POST /pinboards
  # POST /pinboards.json
  def create
    @pinboard = Pinboard.new(pinboard_params)

    respond_to do |format|
      if @pinboard.save
        format.html { redirect_to @pinboard, notice: 'Pinboard was successfully created.' }
        format.json { render :show, status: :created, location: @pinboard }
      else
        format.html { render :new }
        format.json { render json: @pinboard.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pinboards/1
  # PATCH/PUT /pinboards/1.json
  def update
    respond_to do |format|
      if @pinboard.update(pinboard_params)
        format.html { redirect_to @pinboard, notice: 'Pinboard was successfully updated.' }
        format.json { render :show, status: :ok, location: @pinboard }
      else
        format.html { render :edit }
        format.json { render json: @pinboard.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pinboards/1
  # DELETE /pinboards/1.json
  def destroy
    @pinboard.destroy
    respond_to do |format|
      format.html { redirect_to pinboards_url, notice: 'Pinboard was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pinboard
      @pinboard = Pinboard.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pinboard_params
      params.require(:pinboard).permit(:user, :epoch, :articles)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/article_helper.rb
module ArticleHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/pinboards_helper.rb
module PinboardsHelper
end

app/views/articles/_form.html.erb
<%= form_for(@article) do |f| %>
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
      <% @article.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </div>
  <div class="field">
    <%= f.label :pinboard_id %><br>
    <%= f.text_field :pinboard_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<h1>Editing Article</h1>

<%= render 'form' %>

<%= link_to 'Show', @article %> |
<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Articles</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Content</th>
      <th>Pinboard</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @articles.each do |article| %>
      <tr>
        <td><%= article.title %></td>
        <td><%= article.content %></td>
        <td><%= article.pinboard %></td>
        <td><%= link_to 'Show', article %></td>
        <td><%= link_to 'Edit', edit_article_path(article) %></td>
        <td><%= link_to 'Destroy', article, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Article', new_article_path %>

app/views/articles/new.html.erb
<h1>New Article</h1>

<%= render 'form' %>

<%= link_to 'Back', articles_path %>

app/views/articles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @article.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @article.content %>
</p>

<p>
  <strong>Pinboard:</strong>
  <%= @article.pinboard %>
</p>

<%= link_to 'Edit', edit_article_path(@article) %> |
<%= link_to 'Back', articles_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RailsOwlinApi</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/pinboards/_form.html.erb
<%= form_for(@pinboard) do |f| %>
  <% if @pinboard.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pinboard.errors.count, "error") %> prohibited this pinboard from being saved:</h2>

      <ul>
      <% @pinboard.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user %><br>
    <%= f.text_field :user %>
  </div>
  <div class="field">
    <%= f.label :epoch %><br>
    <%= f.number_field :epoch %>
  </div>
  <div class="field">
    <%= f.label :articles %><br>
    <%= f.text_field :articles %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/pinboards/edit.html.erb
<h1>Editing Pinboard</h1>

<%= render 'form' %>

<%= link_to 'Show', @pinboard %> |
<%= link_to 'Back', pinboards_path %>

app/views/pinboards/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Pinboards</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Epoch</th>
      <th>Articles</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pinboards.each do |pinboard| %>
      <tr>
        <td><%= pinboard.user %></td>
        <td><%= pinboard.epoch %></td>
        <td><%= pinboard.articles %></td>
        <td><%= link_to 'Show', pinboard %></td>
        <td><%= link_to 'Edit', edit_pinboard_path(pinboard) %></td>
        <td><%= link_to 'Destroy', pinboard, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Pinboard', new_pinboard_path %>

app/views/pinboards/new.html.erb
<h1>New Pinboard</h1>

<%= render 'form' %>

<%= link_to 'Back', pinboards_path %>

app/views/pinboards/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @pinboard.user %>
</p>

<p>
  <strong>Epoch:</strong>
  <%= @pinboard.epoch %>
</p>

<p>
  <strong>Articles:</strong>
  <%= @pinboard.articles %>
</p>

<%= link_to 'Edit', edit_pinboard_path(@pinboard) %> |
<%= link_to 'Back', pinboards_path %>